#!/usr/bin/python
import networkx as nx
import matplotlib.pyplot as plt

G=nx.Graph()
G.add_node('a1',pos=(1,1))
G.add_node('b1',pos=(2,3))
G.add_node('c1',pos=(4,0))
G.add_node('d1',pos=(3,5))
G.add_edge('a1','b1',weight=0.5)
G.add_edge('b1','c1',weight=9.8)
G.add_edge('c1','d1',weight=4.2)
G.add_node('a2',pos=(7.3, 1.4))
G.add_node('b2',pos=(9,4))
G.add_node('c2',pos=(7,5))
G.add_node('d2',pos=(5.9,3.5))
G.add_edge('a2','b2',weight=0.5)
G.add_edge('b2','c2',weight=9.8)
G.add_edge('c2','d2',weight=4.2)
G.add_edge('a1', 'b2',weight=1)
G.add_edge('b1','c2',weight=2.3)
G.add_edge('c1','d2', weight=4.3)
G.add_edge('a2','b1', weight=7.3)
G.add_edge('b2','c1', weight=5.3)
G.add_edge('c2','d1',weight=6.1)
pos=nx.get_node_attributes(G,'pos')
nx.draw(G,pos,node_size=700)
labels = nx.get_edge_attributes(G,'weight')
nx.draw_networkx_edge_labels(G,pos,edge_labels=labels)
nx.draw_networkx_labels(G,pos,font_size=20,font_family='sans-serif')
plt.savefig("weighted_graph2.png")